<a href="https://colab.research.google.com/github/DevyanshBhattacharya/Basic-Implementation-of-RNN/blob/main/Self_Attention_For_Transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Implementation of Self Attention for Transformer


In [ ]:
import math
import numpy as np

In [ ]:
L,d_k,d_v=4,8,8

In [ ]:
q=np.random.randn(L,d_k)
k=np.random.randn(L,d_k)
v=np.random.randn(L,d_v)


In [ ]:
dat=np.matmul(q,k.T)

In [ ]:
print(dat)

[[-1.21241755 -0.80089127  0.84305403 -0.84838667]
 [ 3.52275505 -0.7319616   1.06258102  0.51265303]
 [-3.06255762  3.91297708 -2.12699367  2.87118119]
 [ 0.46528124 -2.58331123  0.53450799 -1.9575271 ]]


In [ ]:
#Reducing the varience
scale=np.matmul(q,k.T)/math.sqrt(d_k)

In [ ]:
#Masking the unrequired Data
mask=np.tril(np.ones((L,L)))
mask[mask==0]= -np.infty
mask[mask==1]=0

In [ ]:
print(scale+mask)

[[-0.42865434        -inf        -inf        -inf]
 [ 1.24548199 -0.2587875         -inf        -inf]
 [-1.08277763  1.38344631 -0.75200583        -inf]
 [ 0.16450176 -0.91333844  0.18897711 -0.69209034]]


In [ ]:
#Applying softmax ( Converts a vector to a probability Distribution)
def softmax(x):
  return np.exp(x).T/np.sum(np.exp(x),axis=1).T


In [ ]:
attention=softmax(scale+mask)

In [ ]:
print(attention)

[[1.         0.81821039 0.07057197 0.35845972]
 [0.         0.18178961 0.83118887 0.12199452]
 [0.         0.         0.09823916 0.36734139]
 [0.         0.         0.         0.15220437]]


In [ ]:
final=np.matmul(attention,v)
print(final)

[[-0.18127944  0.0222298  -0.80877712 -1.05817772 -0.5240953   0.26064823
  -0.02905582  1.53639602]
 [-0.18773479  0.5646932   1.41841641  0.02446668 -0.495054   -0.1876843
   0.83305194  0.65528957]
 [ 0.052302   -0.01627009  0.64429429 -0.24109246 -0.38917528 -0.30485654
  -0.33371908  0.18176475]
 [ 0.02539486 -0.04358063  0.19669721 -0.12067309 -0.14158091 -0.13350718
  -0.17811768  0.04003029]]
